---
title: "drug activity map"
author: "Muhammad"
date: '2023-04-12'
output: html_document
    code_folding: hide
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align='center')
rm(list = ls())
gc()
source("https://raw.githubusercontent.com/melsadany/workbench/master/msmuhammad-source.R", local = T)

theme_set(theme_minimal())
formatted_tbl <- function(x) {
  kableExtra::kable_styling(knitr::kable(x))
}
```


```{r}
setwd("/Dedicated/jmichaelson-wdata/msmuhammad//projects/brain-drug-map")
library(plotly)
med <- "methylphenidate"
m1.predictions <- read_rds("data/model-derivatives/01_m1-glm-lincs-predictions.rds")
m2.predictions <- read_rds("data/model-derivatives/01_m2-glm-lincs-predictions.rds")
m3.predictions <- read_rds("data/model-derivatives/01_m3-glm-lincs-predictions.rds")

m1.meph <- cbind(m1.predictions %>%
                   select(starts_with("mni"), ends_with("region")),
                 m1.predictions[,med]) %>%
  as.data.frame() %>%
  rename(corr=6) %>%
  mutate(region_2 = sub("_", " ", region)) %>%
  mutate(h_region = sub("rh_", "right ", h_region)) %>%
  mutate(h_region = sub("lh_", "left ", h_region)) %>%
  mutate(h_region = sub("_", " ", h_region))
m2.meph <- cbind(m2.predictions %>%
                   select(starts_with("mni"), ends_with("region")),
                 m2.predictions[,med]) %>%
  as.data.frame() %>%
  rename(corr=6) %>%
  mutate(region_2 = sub("_", " ", region)) %>%
  mutate(h_region = sub("rh_", "right ", h_region)) %>%
  mutate(h_region = sub("lh_", "left ", h_region)) %>%
  mutate(h_region = sub("_", " ", h_region))
m3.meph <- cbind(m3.predictions %>%
                   select(starts_with("mni"), ends_with("region")),
                 m3.predictions[,med]) %>%
  as.data.frame() %>%
  rename(corr=6) %>%
  mutate(region_2 = sub("_", " ", region)) %>%
  mutate(h_region = sub("rh_", "right ", h_region)) %>%
  mutate(h_region = sub("lh_", "left ", h_region)) %>%
  mutate(h_region = sub("_", " ", h_region))

sample <- sample(1:nrow(m1.meph), size = 200000)
plot_ly(m1.meph[sample,], x =~mni_x, y=~mni_y,  z=~mni_z,alpha = 0.7, size = 5) %>%
  add_markers() %>%
  layout()

```

